main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: ggoksu
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: ggoksu
    username: ggoksu
    email: ggoksu@gmail.com
    dev_revision: dev

  s3:
    bucket:
      name: BUCKETNAME
      region: AWSREGION
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
